# Generated by Django 4.1 on 2022-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="omisepayment",
            name="source_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
