# Generated by Django 4.1 on 2022-10-22 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WePay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="user",
            field=models.ManyToManyField(
                related_name="food", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
