# Generated by Django 4.1 on 2022-10-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WePay", "0002_food_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Food",
            new_name="Topic",
        ),
        migrations.AlterField(
            model_name="bankpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="promptpaypayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
