# Generated by Django 4.1.3 on 2022-11-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0002_bills_is_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bills",
            name="is_closed",
        ),
    ]
