# Generated by Django 4.1 on 2022-11-01 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0003_alter_cashpayment_bill_alter_cashpayment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 1, 8, 1, 47, 388846, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="omisepayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 1, 8, 1, 47, 388846, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
