# Generated by Django 4.1.3 on 2022-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0003_remove_bills_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bills",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
