# Generated by Django 4.1 on 2022-10-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WePay", "0003_rename_food_topic_alter_bankpayment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmisePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.localtime)),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("promptpay", "Prompt Pay"),
                            ("internet_banking_scb", "Scb"),
                            ("internet_banking_ktb", "Stb"),
                            ("internet_banking_bbl", "Bbl"),
                            ("internet_banking_bay", "Bay"),
                        ],
                        default="promptpay",
                        max_length=20,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WePay.bills"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_key", models.CharField(default="", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="user",
        ),
        migrations.DeleteModel(
            name="BankPayment",
        ),
        migrations.DeleteModel(
            name="PromptPayPayment",
        ),
        migrations.AddField(
            model_name="omisepayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WePay.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="bills",
            name="header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WePay.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WePay.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="user",
            field=models.ManyToManyField(related_name="food", to="WePay.userprofile"),
        ),
    ]
