# Generated by Django 4.1.3 on 2022-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0004_alter_bills_pub_date_alter_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptpaypayment",
            name="qr",
            field=models.FileField(blank=True, null=True, upload_to="qr/"),
        ),
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-26 23:36:47"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-26 23:36:47", null=True
            ),
        ),
    ]
