# Generated by Django 4.1 on 2022-10-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0004_omisepayment_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="omisepayment",
            name="charge_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PENDING", "Pending"),
                    ("UNPAID", "Unpaid"),
                ],
                default="UNPAID",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="omisepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PENDING", "Pending"),
                    ("UNPAID", "Unpaid"),
                ],
                default="UNPAID",
                max_length=10,
            ),
        ),
    ]
