# Generated by Django 4.1.3 on 2022-11-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0005_promptpaypayment_qr_alter_bills_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-26 23:37:02"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-26 23:37:02", null=True
            ),
        ),
    ]
