# Generated by Django 4.1.3 on 2022-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0005_alter_payment_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="Sat 12 22 21:10:17"),
        ),
    ]
