# Generated by Django 4.1.3 on 2022-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0006_alter_bills_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="Sat 11 22 21:23:07"),
        ),
    ]
