# Generated by Django 4.1.3 on 2022-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0006_alter_bills_pub_date_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-27 19:13:54"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-27 19:13:54", null=True
            ),
        ),
    ]
