# Generated by Django 4.1 on 2022-11-03 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0009_alter_baypayment_date_alter_bblpayment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KTBPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.localtime)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PENDING", "Pending"),
                            ("UNPAID", "Unpaid"),
                        ],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("PromptPay", "Promptpay"),
                            ("SCB", "Scb"),
                            ("KTB", "Ktb"),
                            ("BAY", "Bay"),
                            ("Credit", "Credit"),
                        ],
                        default="Cash",
                        max_length=10,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WePay.bills"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WePay.userprofile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="baypayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="baypayment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="baypayment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="baypayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="baypayment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cashpayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="cashpayment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="cashpayment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="cashpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cashpayment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="user",
        ),
        migrations.DeleteModel(
            name="STBPayment",
        ),
        migrations.AddField(
            model_name="ktbpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
        migrations.AddField(
            model_name="baypayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
        migrations.AddField(
            model_name="bblpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
        migrations.AddField(
            model_name="cashpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
        migrations.AddField(
            model_name="promptpaypayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
        migrations.AddField(
            model_name="scbpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WePay.payment",
            ),
        ),
    ]
