# Generated by Django 4.1.2 on 2022-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WePay', '0011_alter_topic_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
