# Generated by Django 4.1.3 on 2022-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0013_alter_bills_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-12 21:44:27"),
        ),
    ]
