# Generated by Django 4.1 on 2022-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0013_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("PromptPay", "Promptpay"),
                    ("SCB", "Scb"),
                    ("KTB", "Ktb"),
                    ("BAY", "Bay"),
                    ("BBL", "Bbl"),
                ],
                default="Cash",
                max_length=10,
            ),
        ),
    ]
