# Generated by Django 4.1.3 on 2022-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0014_alter_bills_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-12 22:11:26"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-12 22:11:26", null=True
            ),
        ),
    ]
