# Generated by Django 4.1 on 2022-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0015_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="baypayment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bblpayment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ktbpayment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="promptpaypayment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scbpayment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
