# Generated by Django 4.1.3 on 2022-11-13 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0016_alter_bills_pub_date_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baypayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
        migrations.AlterField(
            model_name="bblpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-13 11:26:44"),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
        migrations.AlterField(
            model_name="ktbpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-13 11:26:44", null=True
            ),
        ),
        migrations.AlterField(
            model_name="promptpaypayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
        migrations.AlterField(
            model_name="scbpayment",
            name="payment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="WePay.payment",
            ),
        ),
    ]
