# Generated by Django 4.1 on 2022-11-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0016_baypayment_uri_bblpayment_uri_ktbpayment_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
