# Generated by Django 4.1 on 2022-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0017_alter_bills_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
