# Generated by Django 4.1.3 on 2022-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0017_alter_baypayment_payment_alter_bblpayment_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="pub_date",
            field=models.DateTimeField(default="2022-11-17 23:05:34"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, default="2022-11-17 23:05:34", null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PENDING", "Pending"),
                    ("UNPAID", "Unpaid"),
                    ("FAIL", "Fail"),
                    ("EXPIRED", "Expired"),
                ],
                default="UNPAID",
                max_length=10,
            ),
        ),
    ]
