# Generated by Django 4.1 on 2022-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0017_alter_bills_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bills",
            name="is_created",
            field=models.BooleanField(default=False),
        ),
    ]
