# Generated by Django 4.1.3 on 2022-11-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0018_alter_bills_pub_date_alter_payment_date_and_more"),
        ("WePay", "0018_alter_bills_pub_date_alter_payment_date_and_more 2"),
    ]

    operations = []
