# Generated by Django 4.1 on 2022-11-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0018_bills_is_created"),
        ("WePay", "0019_remove_userprofile_display_name"),
    ]

    operations = []
