# Generated by Django 4.1.3 on 2022-11-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0020_merge_20221107_1311"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baypayment",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="bblpayment",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="ktbpayment",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="promptpaypayment",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="scbpayment",
            name="uri",
        ),
        migrations.AddField(
            model_name="payment",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
