# Generated by Django 4.1.3 on 2022-11-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0021_remove_baypayment_uri_remove_bblpayment_uri_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="chain_key",
            new_name="chain_id",
        ),
    ]
