# Generated by Django 4.1 on 2022-10-30 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0002_alter_cashpayment_bill_alter_omisepayment_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashpayment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WePay.bills"
            ),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 30, 13, 10, 0, 936312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="omisepayment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WePay.bills"
            ),
        ),
        migrations.AlterField(
            model_name="omisepayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 30, 13, 10, 0, 936312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
