# Generated by Django 4.1 on 2022-11-03 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0005_baypayment_bblpayment_promptpaypayment_scbpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baypayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bblpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="promptpaypayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="scbpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stbpayment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 3, 6, 47, 62361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
