# Generated by Django 4.1 on 2022-11-03 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("WePay", "0008_baypayment_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baypayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="bblpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="cashpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="promptpaypayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="scbpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="stbpayment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
