name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_TIME_ZONE: ${{ secrets.TIME_ZONE }}
          envkey_OMISE_PUBLIC: ${{ secrets.OMISE_PUBLIC }}
          envkey_OMISE_SECRET: ${{ secrets.OMISE_SECRET }}
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          envkey_CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          envkey_CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          envkey_CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r --use-pep517 requirements.txt
          pip install coverage selenium
      - name: Run Tests
        run: |
          coverage run manage.py test --exclude-tag=e2e
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
