name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0

        